### PR TITLE
Added explicit start = 0 modifiers to parameters without default binding

### LINKED ISSUE #171: Models with experiment annotation that have parameters without bindings and without explicitly set start values in Buildings
Dear ThermoFluidStream developers,

please check the latest OpenModelica [regression test report](https://libraries.openmodelica.org/branches/history/master/2024-03-06%2022:42:24..2024-03-07%2022:25:06.html). There are a few ThermoFluidStream models that fail since we fixed ticket OpenModelica/OpenModelica#10386.

According to the latest version of Modelica Specification, i.e., 3.6, when you simulate a model all parameters with `fixed = true` should have a binding equation (either provided as a default in the components, or set by modifiers when instantiating them). The only exception is parameters that have an explicitly set start attribute - in that case, if a binding equation is lacking, the start attribute is used to set the parameter value and a warning should be issued.

You can
- add a default binding to the parameters in the component definitions, or
- add an explicit bining when you instantiate the components or,
- add an explicit start = 0 attribute to the parameters in the component definition, which will be used as a fallback value, with a warning being issued.

This will make those models compliant with the Modelica Specification in force, and get them running again in OpenModelica.

Thanks!

### PR DESCRIPTION
**Pull request by casella**
This fixes #171.

### CODE REVIEW

**Comment by dzimmer** [comment]
Will be substituted by a PR on #171 from @tobolar.  (see discussion)
Thank you for suggesting a first solutions and make us think about it.

**Comment by casella** [comment]
Not sure #171 is good either, see [comment](https://github.com/DLR-SR/ThermofluidStream/issues/171#issuecomment-2207020059).

**Comment by dzimmer** [comment]
I will not accept this PR as is but your latest suggestion of #171 with the assert statement seems good to me.  
I have reopened this PR in case you want to do the changes. I can do it as well but I won't do it before Friday. Now I feel my jetlag. I fail to write English... I shall not code Modelica...

**Comment by dzimmer** [comment]
substituted by #201 according to discussion in #171

**Pull request closed without merging**
